[pytest]
testpaths =
    01-black-scholes/tests
    02-markowitz/tests
    03-vol-smile/tests
    04-oscillateurs/tests
    05-edp-chaleur-ondes/tests
    06-schrodinger/tests
    07-pagerank/tests
    08-ml-from-scratch/tests
    09-crypto-info/tests
addopts = -q
